### PR TITLE
Fail startup if collector configuration dir is not absolute

### LINKED ISSUE #309: The "collector_configuration_directory" option requires an absolute path
### Problem description

The value of the `collector_configuration_directory` config option needs to be an absolute path. I tried to use `.cache/config` as value. Writing the config file worked but starting the collector didn't because it couldn't find the file.

Filebeat error log:
```
Exiting: error loading config file: stat .cache/config/filebeat-6.3.0.conf: no such file or directory
```

Sidecar output:
```
$ ./build/1.0.0/linux/amd64/graylog-sidecar -c local.yml 
INFO[0000] Using node-id: 1c4a8275-ffeb-4c27-8cfb-cd23ff5a52e8 
INFO[0000] Starting signal distributor                  
INFO[0005] Adding process runner for: filebeat-6.3.0    
INFO[0005] [filebeat-6.3.0] Configuration change detected, rewriting configuration file. 
INFO[0005] [filebeat-6.3.0] Starting (exec driver)      
ERRO[0006] [filebeat-6.3.0] Backend finished unexpectedly, trying to restart 1/3. 
INFO[0006] [filebeat-6.3.0] Starting (exec driver)      
ERRO[0007] [filebeat-6.3.0] Backend finished unexpectedly, trying to restart 2/3. 
INFO[0007] [filebeat-6.3.0] Starting (exec driver)      
ERRO[0008] [filebeat-6.3.0] Backend finished unexpectedly, trying to restart 3/3. 
INFO[0008] [filebeat-6.3.0] Starting (exec driver)      
ERRO[0009] [filebeat-6.3.0] Unable to start collector after 3 tries, giving up! 
```

I think we should either require an absolute path and warn the user if the path is not absolute or change the code to handle relative paths.

### Steps to reproduce the problem

1. Use relative path for `collector_configuration_directory` config option
1. Start sidecar
1. Assign configuration
1. Watch collector startup fail

### Environment

* Sidecar Version: 1.0.0-alpha.9

### PR DESCRIPTION
**Pull request by mpfz0r**
Also try to create the directory right away.
It's easier to debug if we fail early.

Fixes #309

### CODE REVIEW

File: context/context.go [hunk 1]
```diff
@@ -104,6 +104,13 @@ func (ctx *Ctx) LoadConfig(path *string) error {
 	if ctx.UserConfig.CollectorConfigurationDirectory == "" {
 		log.Fatal("No collector configuration directory was configured.")
 	}
+	if !filepath.IsAbs(ctx.UserConfig.CollectorConfigurationDirectory) {
+		log.Fatal("Collector configuration directory must be an absolute path.")
+	}
+	err = common.CreatePathToFile(ctx.UserConfig.CollectorConfigurationDirectory)
+	if err != nil {
```
Comment (bernd) [inline context/context.go]: This doesn't fail on sidear startup:

```
$ fgrep configuration_directory local.yml 
collector_configuration_directory: "/foo"
$ ./build/1.0.0/linux/amd64/graylog-sidecar -c local.yml 
INFO[0000] Using node-id: 1c4a8275-ffeb-4c27-8cfb-cd23ff5a52e8 
INFO[0000] Starting signal distributor                  
INFO[0015] Adding process runner for: filebeat-6.3.0    
INFO[0015] [filebeat-6.3.0] Configuration change detected, rewriting configuration file. 
INFO[0015] Trying to create directory for: /foo/filebeat-6.3.0.conf 
ERRO[0015] Not able to create directory path: /foo      
```

I see the error only when the sidecar tries to write the config file but the sidecar keeps running.

Comment (mpfz0r) [reply context/context.go]: Ah, that's because you've tested it with a directory that was already there (`/`)
I improved the test so it would not ignore the last directory of the path.
