### PR TITLE
Make run directory configurable

### LINKED ISSUE #58: Run directory not configurable (fails when non-root user)
_From @ente187 on September 19, 2016 11:26_

Hello Mates,

i was recommented to create a GH-Issue, so here is my issue. Hope you can help me out :)
i would like to achieve an architecture like shown on the left side of this picture(because i want to use NXLog): http://docs.graylog.org/en/2.1/_images/sidecar_overview.png. I have already installed Graylog2 on my RedHat Server and now i'm currently working on the configuration of collector-sidecar. As i'm working as nonroot, i had to change several directories in configuration files of collector-sidecar and NXLog. Now to the problem: Everytime i try to start collector sidecar, i get INFO/Error- Messages: 

```
[gunge@bsul0959 bin]$ ./graylog-collector-sidecar -c /opt/ansible/sidecar/etc/graylog/collector-sidecar/collector_sidecar.yml
INFO[0000] Using collector-id: 13a3d80f-cb69-4391-8520-7a760b9b964e
INFO[0000] Fetching configurations tagged by: [linux apache syslog]
ERRO[0000] stat /var/run/graylog/collector-sidecar: no such file or directory
INFO[0000] Trying to create directory for: /var/run/graylog/collector-sidecar/nxlog.run
ERRO[0000] Not able to create directory path: /var/run/graylog/collector-sidecar
INFO[0000] Starting collector supervisor
ERRO[0010] [UpdateRegistration] Sending collector status failed. Disabling `send_status` as fallback! PUT http://127.0.0.1:12900/plugins/org.graylog.plugins.collector/collectors/13a3d80f-cb69-4391-8520-7a760b9b964e: 400 Unable to map property tags.
Known properties include: operating_system
```

 After this start procedure, a collector appears on my Graylog Web-Interface, but if i abort the start procedure, the collector disappears again. During the start procedure, it tries to create a path in /var/run/graylog/collector-sidecar but as i am not root, it can't. As a consequence, he can't create nxlog.run in that directory. I already tried to change the path to a place where i don't need root permissions, but i think there is no configuration file where i can do this. So i looked into the binary of collector-sidecar and found this:

```
func (nxc *NxConfig) ValidatePreconditions() bool {
     if runtime.GOOS == "linux" {
          if !common.IsDir("/var/run/graylog/collector-sidecar") {
                err := common.CreatePathToFile("/var/run/graylog/collector-sidecar/nxlog.run")
                if err != nil {
                     return false
                }
          }
     }
     return true
}
```
It seems, that the path is coded into the application and there is no way to configure anoter path. Do you see a solution besides getting root permissions?

Thank you in advance!

 

## Steps to Reproduce (for bugs)
Here is an example on how to configure and start collecor sidecar: 
[http://docs.graylog.org/en/2.1/pages/collector_sidecar.html](url)

## Context

Here is the collector that appears when i try to start Collector-Sidecar:
collector
This is my collector_sidecar.yml:
collector sidecaryml
This is the NXLog conf file:
nxlogconf

**Environment**

- Linux version 2.6.32-573.18.1.el6.x86_64 (mockbuild@x86-010.build.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) )
- Architecture:          x86_64
- CPU op-mode(s):        32-bit, 64-bit
- Byte Order:            Little Endian
- CPU(s):                8
- On-line CPU(s) list:   0-7
- Thread(s) per core:    1
- Core(s) per socket:    1
- Socket(s):             8
- NUMA node(s):          1
- Vendor ID:             GenuineIntel
- CPU family:            6
- Model:                 13
- Stepping:              3
- CPU MHz:               3192.306
- BogoMIPS:              6384.61
- Hypervisor vendor:     KVM
- Virtualization type:   full
- L1d cache:             32K
- L1i cache:             32K
- L2 cache:              4096K
- NUMA node0 CPU(s):     0-7

**Graylog Version:** Graylog 2.0.0
**Collector Sidecar: 0.0.9-1.x86_64
**Elasticsearch Version:** elasticsearch-2.3.2
**MongoDB Version:** v3.2.6
**Operating System:** Linux version 2.6.32-573.18.1.el6.x86_64 (mockbuild@x86-010.build.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) )
**Browser version:** IE 11.0.9600.18426

_Copied from original issue: Graylog2/graylog2-server#2850_

### PR DESCRIPTION
**Pull request by mariussturm**
The actual configuration happens in the `default-snippet`. The Sidecar checks that the PID file directory exist and in doubt creates it. This needs to be configurable in case the `PidFile` option in the `default-snippet` is changed by the user, e.g. to run the sidecar as non-root user.
Fixes #58

### CODE REVIEW

File: backends/nxlog/nxlog.go [hunk 1]
```diff
@@ -84,8 +84,12 @@ func (nxc *NxConfig) ExecArgs() []string {
...
 func (nxc *NxConfig) ValidatePreconditions() bool {
 	if runtime.GOOS == "linux" {
-		if !common.IsDir("/var/run/graylog/collector-sidecar") {
-			err := common.CreatePathToFile("/var/run/graylog/collector-sidecar/nxlog.run")
+		runDir := "/var/run/graylog/collector-sidecar" // set in default-snippet
+		if nxc.UserConfig.RunPath != "" {
+			runDir = nxc.UserConfig.RunPath
+		}
+		if !common.IsDir(runDir) {
+			err := common.CreatePathToFile(filepath.Join(runDir, "nxlog.run"))
```
Comment (bernd) [inline backends/nxlog/nxlog.go]: Should we log something if to indicate what went wrong? Like when the permissions on the directory are wrong.

Comment (mariussturm) [inline backends/nxlog/nxlog.go]: Yes, good point.
