### PR TITLE
Exit with return code 1 if config parsing failed

### LINKED ISSUE #220: running -configtest returns wrong exit code with an invalid config
### Problem description
a failed -configtest returns wrong exit code

### Steps to reproduce the problem
create an invalid configuration
/etc/graylog/collector-sidecar/collector_sidecar.yml
--- 
  server_url: "http://127.0.0.1:9000/api/"
  update_interval: CHANGEME

[vagrant@localhost ruby]$ graylog-collector-sidecar -configtest
Loading configuration file failed.
[vagrant@localhost ruby]$ echo $?
0

* sidecar Version:
[vagrant@localhost ruby]$ graylog-collector-sidecar -version
Graylog Collector Sidecar version 0.1.4 (edd1e1d) [go1.8.3/amd64]

* Operating System: 
centos 7

### PR DESCRIPTION
**Pull request by joschi**
In order to programmatically use the `-configtest` command and handle any other error with regard to configuration parsing, Collector Sidecar should exit with an exit code != 0 to indicate an error.

Fixes #220

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -105,8 +103,7 @@ func main() {
 	ctx := context.NewContext()
 	err = ctx.LoadConfig(configurationFile)
 	if err != nil {
-		fmt.Println("Loading configuration file failed.")
-		return
+		log.Fatalln("Loading configuration file failed.")
```
Comment (mariussturm) [inline main.go]: The reason for using fmt was to not show the user a log line on stdout. With log.Fatal the uers gets `FATA[0000] Loading configuration file failed.` What looks kind of odd to me.

File: main.go [hunk 2]
```diff
@@ -150,7 +147,7 @@ func commandLineSetup() error {
 	}
 
 	if _, err := os.Stat(*configurationFile); os.IsNotExist(err) {
-		return errors.New("Can not open collector-sidecar configuration " + *configurationFile)
+		return errors.New("Unable to open configuration file " + *configurationFile)
```
Comment (mariussturm) [inline main.go]: I would also add a colon here: `file: `

File: main.go (hunk 1 above)
Comment (joschi) [reply main.go]: At least it's consistent with the rest of the output (if any).

But if you want it differently, we can simply replace the `return` with `os.Exit(1)`.

Comment (mariussturm) [reply main.go]: Yes, I would prefer os.Exit here. The difference is that the config test is usually issued manually by the user, the output is presented directly to the console. The rest of the Sidecar runs typically as a background daemon, so log files with a proper log format are the way to print stuff.

Comment (joschi) [reply main.go]: > The difference is that the config test is usually issued manually by the user, the output is presented directly to the console.

I'm not sure this is often the case.

When using configuration management (or even in init scripts), a validation of the configuration file is performed before the service is restarted, so that an invalid configuration wouldn't lead to service downtime.

**Comment by mariussturm** [comment]
Thanks!
